[WIP]テーブル設計
kotasho/chat-space pull request #2
Opened 2019-04-14 08:16 UTC by kotasho

WHAT # 
テーブルを設計し実装する
WHY # 
複数のユーザー、グループが関係し合うサービスに必要な土台となる為

2019-04-14 08:17 UTC, ghost requested changes
membersテーブルだけでなく、groupsテーブルやusersテーブルなども記載をお願い致します。

2019-04-14 08:17 UTC, hiroki5123 commented on README.md
> +## membersテーブル
全てのテーブル構造を記載してください。

2019-04-14 09:58 UTC, kotasho commented
修正しました。
ご確認をお願いいたします。

2019-04-17 06:29 UTC, kotasho commented on README.md
> +## membersテーブル
修正いたしました。
ご確認をお願いいたします。

2019-04-20 07:33 UTC, kotasho commented on README.md
> +## membersテーブル
前回、pushがうまくいっていなかったみたいです・・申し訳ありませんが、もう一度ご確認のほどよろしくお願いいたします。

2019-04-21 03:00 UTC, merged