非同期通信の実装
kotasho/chat-space pull request #8
Opened 2019-04-26 09:50 UTC by kotasho

# WHAT
非同期通信の実装
# WHY
非同期通信はデータ通信のリクエストを出してからレスポンスを待つ間にも操作ができるなどユーザーの利便性を向上させる

2019-04-26 10:02 UTC, i-date reviewed
ご提出ありがとうございます！コメントいたしました^^

2019-04-26 10:02 UTC, i-date commented on app/assets/javascripts/message.js
> +    console.log(data)
こちら不要でしたら削除しましょう。

2019-04-26 10:02 UTC, i-date commented on app/assets/javascripts/message.js
> +    //$('.hidden').val('')
こちらも

2019-04-26 10:02 UTC, i-date commented on app/assets/javascripts/message.js
> +    $('.form__message').val('');
フォームをリセットするreset()を使用してはいかがでしょうか？少し調べてみましょう。

2019-04-26 10:02 UTC, i-date commented on app/views/messages/create.json.jbuilder
> +json.image  @message.image.url
最下行は空行にしましょう。

2019-04-26 10:02 UTC, i-date commented on app/assets/javascripts/message.js
> +                 ${message.content}
こちらcontentはあるようですが、imageはないのでしょうか？

2019-04-26 10:02 UTC, i-date commented on app/assets/javascripts/message.js
> +  console.log(1)
こちら不要でしたら削除しましょう。

2019-04-26 12:21 UTC, kotasho commented on app/assets/javascripts/message.js
> +    $('.form__message').val('');
resetフォームは調べましたが、上手く行かなかったので実装はしませんでした。それ以外の部分は修正しましたのでご確認をお願いいたします。

2019-04-27 02:55 UTC, kotasho commented on app/assets/javascripts/message.js
> +    console.log(data)
修正しました

2019-04-27 02:56 UTC, kotasho commented on app/assets/javascripts/message.js
> +    //$('.hidden').val('')
修正しました

2019-04-27 02:56 UTC, kotasho commented on app/views/messages/create.json.jbuilder
> +json.image  @message.image.url
修正しました

2019-04-27 02:56 UTC, kotasho commented on app/assets/javascripts/message.js
> +                 ${message.content}
修正しました

2019-04-27 02:56 UTC, kotasho commented on app/assets/javascripts/message.js
> +  console.log(1)
修正しました

2019-04-27 06:30 UTC, kotasho commented
修正しました

2019-04-27 06:58 UTC, TOMARUMARU commented on app/assets/javascripts/message.js
> +    var imagehtml = message.image == `<img src="${message.image}" class="lower-message__image">`
定義されてるだけで使用されてませんね

2019-04-27 06:58 UTC, TOMARUMARU commented on app/views/messages/_message.html.haml
> +
改行は一番下に1行だけで大丈夫です

2019-04-27 07:10 UTC, kotasho commented
修正いたしました

2019-04-27 07:14 UTC, yuki-uchida requested changes

2019-04-27 07:14 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +  function buildHTML(message){
なんのHTMLをbuildするかわかる名前にしましょう

2019-04-27 07:14 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +  .done(function(data){
dataよりも具体的な名前にしましょう

2019-04-27 07:25 UTC, TOMARUMARU commented on app/assets/javascripts/message.js
> +});
こちらのファイルのインデント見直しましょう

2019-04-27 07:27 UTC, kotasho commented
修正してみました。
ご確認のほどよろしくお願いいたします。

2019-04-27 07:31 UTC, yuki-uchida commented
LGTMです。お疲れ様でした

2019-04-27 07:31 UTC, merged